spring.application.name=delivery-api

# URL do banco de dados em memória
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar o console web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações do Hibernate/JPA (opcional)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
