spring.application.name=delivery-api

# URL do banco de dados em memória
spring.datasource.url=${DATABASE_URL}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# Habilitar o console web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações do Hibernate/JPA (opcional)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql= true

# Configurações do flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

#config do data.sql pra teste
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true



