
-- V1 - CRIAÇÃO DA ESTRUTURA DO BANCO

-- USER
CREATE TABLE tb_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255) NOT NULL,
    phone    VARCHAR(255) NOT NULL,
    email    VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

-- CATEGORY
CREATE TABLE tb_category
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255),
    description VARCHAR(255)
);

-- ADDRESS
CREATE TABLE tb_address
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cep     VARCHAR(255),
    rua     VARCHAR(255),
    numero  VARCHAR(255),
    bairro  VARCHAR(255),
    cidade  VARCHAR(255),
    longitude DOUBLE,
    latitude DOUBLE,
    user_id BIGINT,

    CONSTRAINT fk_address_user
        FOREIGN KEY (user_id)
            REFERENCES tb_user (id)
);

-- PRODUCT
CREATE TABLE tb_product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255),
    marca       VARCHAR(255),
    description VARCHAR(255),
    image_url   VARCHAR(255),
    price       DECIMAL(19, 2),
    active      BOOLEAN NOT NULL,
    category_id BIGINT,

    CONSTRAINT fk_product_category
        FOREIGN KEY (category_id)
            REFERENCES tb_category (id)
);

-- PRODUCT VARIANT
CREATE TABLE tb_product_variant
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    size       VARCHAR(255),
    color      VARCHAR(255),
    sku        VARCHAR(255) NOT NULL UNIQUE,
    price      DECIMAL(19, 2),
    active     BOOLEAN,
    product_id BIGINT       NOT NULL,

    CONSTRAINT fk_variant_product
        FOREIGN KEY (product_id)
            REFERENCES tb_product (id)
);

-- STORE
CREATE TABLE tb_store
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255),
    cnpj       VARCHAR(255),
    phone      VARCHAR(255),
    active     BOOLEAN NOT NULL,
    address_id BIGINT  NOT NULL,

    CONSTRAINT fk_store_address
        FOREIGN KEY (address_id)
            REFERENCES tb_address (id)
);