-- V1 - CRIAÇÃO DA ESTRUTURA DO BANCO

-- USER
CREATE TABLE tb_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255) NOT NULL,
    phone    VARCHAR(255) NOT NULL,
    email    VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

-- CATEGORY
CREATE TABLE tb_category
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL
);

-- ADDRESS
CREATE TABLE tb_address
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cep       VARCHAR(255) NOT NULL,
    rua       VARCHAR(255) NOT NULL,
    numero    VARCHAR(255) NOT NULL,
    bairro    VARCHAR(255) NOT NULL,
    cidade    VARCHAR(255) NOT NULL,
    longitude DOUBLE PRECISION,
    latitude  DOUBLE PRECISION,
    user_id   BIGINT,

    CONSTRAINT fk_address_user
        FOREIGN KEY (user_id)
            REFERENCES tb_user (id)
);

-- PRODUCT
CREATE TABLE tb_product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    marca       VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    image_url   VARCHAR(255),
    price       DECIMAL(19, 2) NOT NULL,
    active      BOOLEAN NOT NULL,
    category_id BIGINT NOT NULL,

    CONSTRAINT fk_product_category
        FOREIGN KEY (category_id)
            REFERENCES tb_category (id)
);

-- PRODUCT VARIANT
CREATE TABLE tb_product_variant
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    size       VARCHAR(255) NOT NULL,
    color      VARCHAR(255) NOT NULL,
    sku        VARCHAR(255) NOT NULL UNIQUE,
    price      DECIMAL(19, 2) NOT NULL,
    active     BOOLEAN NOT NULL,
    product_id BIGINT NOT NULL,

    CONSTRAINT fk_variant_product
        FOREIGN KEY (product_id)
            REFERENCES tb_product (id)
);

-- STORE
CREATE TABLE tb_store
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    cnpj       VARCHAR(255) NOT NULL,
    phone      VARCHAR(255) NOT NULL,
    active     BOOLEAN NOT NULL,
    address_id BIGINT NOT NULL,

    CONSTRAINT fk_store_address
        FOREIGN KEY (address_id)
            REFERENCES tb_address (id)
);